// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkuS3oyQUIhxHsoUMdZeY4kkKh7f0EBD0',
    appId: '1:903029544056:web:64146f12f8dae925c1898d',
    messagingSenderId: '903029544056',
    projectId: 'assignment-firebase-b481f',
    authDomain: 'assignment-firebase-b481f.firebaseapp.com',
    storageBucket: 'assignment-firebase-b481f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt5urHKwP7APcegjNEFX6yYOJwvwV6LiQ',
    appId: '1:903029544056:android:187ebaea2a056b7ec1898d',
    messagingSenderId: '903029544056',
    projectId: 'assignment-firebase-b481f',
    storageBucket: 'assignment-firebase-b481f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0KwiRJUqu05PW5PcCWw4sGvhEJLql7k',
    appId: '1:903029544056:ios:13d8090dc504f753c1898d',
    messagingSenderId: '903029544056',
    projectId: 'assignment-firebase-b481f',
    storageBucket: 'assignment-firebase-b481f.firebasestorage.app',
    iosBundleId: 'com.example.assignmentFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf0KwiRJUqu05PW5PcCWw4sGvhEJLql7k',
    appId: '1:903029544056:ios:13d8090dc504f753c1898d',
    messagingSenderId: '903029544056',
    projectId: 'assignment-firebase-b481f',
    storageBucket: 'assignment-firebase-b481f.firebasestorage.app',
    iosBundleId: 'com.example.assignmentFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkuS3oyQUIhxHsoUMdZeY4kkKh7f0EBD0',
    appId: '1:903029544056:web:6b7bc6fc34a80cf7c1898d',
    messagingSenderId: '903029544056',
    projectId: 'assignment-firebase-b481f',
    authDomain: 'assignment-firebase-b481f.firebaseapp.com',
    storageBucket: 'assignment-firebase-b481f.firebasestorage.app',
  );
}
